version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: build
          command: yarn install
      - run:
          name: lint
          command: yarn lint
      - run: 
          name: test
          command: yarn test